name: Model Airplanes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.125
  lightness: 0.8619404889177531
  saturation: 0.2166902932804078
  rhythmicContrast: 0.8178687018807977
purpose: []
